name: test

on: push

jobs:
  unit-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        - {name: Linux, python: '3.14', os: ubuntu-latest}
        - {name: Windows, python: '3.14', os: windows-latest}
        - {name: Mac, python: '3.14', os: macos-latest}
        - {name: '3.13', python: '3.13', os: ubuntu-latest}
        - {name: '3.12', python: '3.12', os: ubuntu-latest}
        - {name: '3.11', python: '3.11', os: ubuntu-latest}
    steps:
    - name: Check out repository
      uses: actions/checkout@v7
    - uses: extractions/setup-just@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install Typst
      run: just install-typst
    - name: Run tests
      run: just test
